# Generated by Django 3.1.3 on 2020-11-06 20:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaseProducao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição da fase de produção')),
                ('sigla', models.CharField(max_length=6, verbose_name='Sigla da fase de produção')),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Localização')),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Raça')),
            ],
        ),
        migrations.CreateModel(
            name='TipoGranja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição do tipo da granja')),
                ('sigla', models.CharField(max_length=6, verbose_name='Sigla do tipo da granja')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID do animal')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do animal')),
                ('tipo_animal', models.CharField(choices=[('POULTRY', 'POULTRY'), ('SWINE', 'SWINE')], default='', max_length=7, verbose_name='Tipo do animal')),
                ('status_animal', models.IntegerField(choices=[(0, 'Ativo'), (1, 'Inativo'), (2, 'Vendido'), (3, 'Descartado')], default=0, max_length=1, verbose_name='Status do animal')),
                ('data_nascimento', models.DateTimeField(verbose_name='Data de cadastro')),
                ('entrada_plantel', models.DateField(verbose_name='Data de entrada no plantel')),
                ('peso_compra', models.DecimalField(decimal_places=3, max_digits=6)),
                ('codigo_rastreamento', models.CharField(max_length=50, verbose_name='Código de rastreamento do animal')),
                ('fase_producao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='granja.faseproducao', verbose_name='Fase de produção do animal')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='granja.localizacao', verbose_name='Localização do animal na granja')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='granja.raca', verbose_name='Raça do animal')),
                ('tipo_granja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='granja.tipogranja', verbose_name='Tipo de granja')),
            ],
        ),
    ]
