# Generated by Django 3.1.3 on 2020-11-07 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('granja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='codigo_rastreamento',
            field=models.CharField(max_length=50, verbose_name='Código de rastreamento'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='fase_producao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='granja.faseproducao', verbose_name='Fase de produção'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='localizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='granja.localizacao', verbose_name='Localização na granja'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='granja.raca', verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status_animal',
            field=models.IntegerField(choices=[(0, 'Ativo'), (1, 'Inativo'), (2, 'Vendido'), (3, 'Descartado')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tipo_animal',
            field=models.CharField(choices=[('POULTRY', 'POULTRY'), ('SWINE', 'SWINE')], default='', max_length=7, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='faseproducao',
            name='descricao',
            field=models.CharField(max_length=150, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='faseproducao',
            name='sigla',
            field=models.CharField(max_length=6, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='tipogranja',
            name='descricao',
            field=models.CharField(max_length=150, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tipogranja',
            name='sigla',
            field=models.CharField(max_length=6, verbose_name='Sigla'),
        ),
        migrations.CreateModel(
            name='Granja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Granja')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granja_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('usuarios', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='granja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='granja.granja', verbose_name='Granja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localizacao',
            name='granja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='granja.granja', verbose_name='Granja'),
            preserve_default=False,
        ),
    ]
