# Generated by Django 3.1.3 on 2020-11-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0002_auto_20201107_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='granja',
            name='endereco',
            field=models.CharField(default='Rua São Sebastião, 19 - Maceió, AL', max_length=400, verbose_name='Endereço da Granja'),
            preserve_default=False,
        ),
    ]
