# Generated by Django 3.1.3 on 2020-11-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0003_granja_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='codigo_rastreamento',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de rastreamento'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='faseproducao',
            name='sigla',
            field=models.CharField(max_length=6, unique=True, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='nome',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nome da Localização'),
        ),
        migrations.AlterField(
            model_name='raca',
            name='nome',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nome da Raça'),
        ),
        migrations.AlterField(
            model_name='tipogranja',
            name='sigla',
            field=models.CharField(max_length=6, unique=True, verbose_name='Sigla'),
        ),
    ]
