# Generated by Django 3.1.3 on 2020-11-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='nome',
            field=models.CharField(default='Tyago Goulart', max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
